language: generic
os: linux
dist: xenial
services:
  - docker

before_install:
  - docker build -t korkhan/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true korkhan/docker-react npm run test
